language: python

python:
  - 2.7
  - 3.4

env:
  - DJANGO_VERSION=1.4.10
  - DJANGO_VERSION=1.5.12
  - DJANGO_VERSION=1.6.11
  - DJANGO_VERSION=1.7.7
  - DJANGO_VERSION=1.8

before_install:
 - sudo apt-get update > /dev/null
 - sudo apt-get install -y python-software-properties
 - sudo apt-add-repository -y ppa:ubuntugis/ppa
 - sudo apt-get update > /dev/null

install:
 - pip install jsonfield
 - sudo apt-get install -y libgdal-dev libproj-dev libgeos-dev libspatialite-dev
 - if [[ $TRAVIS_PYTHON_VERSION == "2.7" ]]; then pip install git+git://github.com/tinio/pysqlite.git@extension-enabled#egg=pysqlite; fi
   # This is a dependency of our Django test script
 - pip install argparse --use-mirrors

 - pip install -q Django==$DJANGO_VERSION --use-mirrors

 - pip install coverage

 - pip install flake8 --use-mirrors

 - python setup.py develop

before_script:
 - flake8 --ignore=E501 djgeojson

script:
 - coverage run quicktest.py djgeojson

after_success:
 - pip install coveralls
 - coveralls

matrix:
    exclude:
        - python: 3.3
          env: DJANGO_VERSION=1.4.10
