dist: xenial
sudo: required

language: python

python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8

addons:
  apt:
    sources:
    - sourceline: ppa:ubuntugis/ppa
    packages:
    - gdal-bin
    - libgdal-dev
    - libproj-dev
    - spatialite-bin
    - python3-dev
    - libsqlite3-mod-spatialite

env:
  - DJANGO_VERSION=2.2.16
  - DJANGO_VERSION=3.0.10
  - DJANGO_VERSION=3.1.2

install:
   # This is a dependency of our Django test script
 - CPLUS_INCLUDE_PATH=/usr/include/gdal C_INCLUDE_PATH=/usr/include/gdal CFLAGS=-I/usr/include/gdal pip install GDAL==2.2.4

 - pip install jsonfield Django==$DJANGO_VERSION
 - pip install coverage coveralls argparse flake8
 - python setup.py develop

before_script:
 - flake8 --ignore=E501,W504 djgeojson

script:
 - coverage run quicktest.py djgeojson

after_success:
 - coveralls

matrix:
    exclude:
        - python: 3.5
          env: DJANGO_VERSION=3.0.10
        - python: 3.5
          env: DJANGO_VERSION=3.1.2
